import { create } from "zustand";
import { persist } from "zustand/middleware";
import type { AssetCode } from "@/lib/assets";
import { useWalletStore } from "@/store/wallet";
import {
  buildCreateGroupVault, buildDeposit, buildCcpWithdraw, buildCancel, buildClaimPool,
  buildCreateGroupVaultZk, buildDepositZk, buildDepositZkUltraHonk, buildWithdrawZk, buildClaimPoolZk,
  getGroupVault, getVaultsByMember, getVaultsByCreator, getMemberState, getCcpPoolBalance,
  getZkVault, getZkMemberRecord, getVaultPrivacyMode,
  submitCcpTx, fromStroops, toStroops, bpsToPercent, TOKEN_ADDRESS,
  deriveSecretFromAddress, computeZkDepositCommitment, buildZkDepositProof, deriveZkBlindingFactor, buildZkEarlyExitProof,
  type GroupVaultOnChain, type MemberRecordOnChain, type CcpVaultState, type CcpMemberState,
  vaultStateLabel, memberStateLabel,
} from "@/lib/ccp-contract";

// ─── Frontend types ───────────────────────────────────────────────────────────

export type GroupVaultStatus = "funding" | "active" | "settlement" | "resolved" | "cancelled";

export interface MemberEntry {
  address: string;
  amount: number;       // human-readable
  state: string;        // label
  rawState: CcpMemberState | null;
  commitment?: string;  // member_commitment for ZK vaults
  obligationStroops?: string; // raw stroops as string (for JSON-safe persist)
}

export interface ZkMemberSecret {
  address: string;
  secret: string;
  commitment: string;
  slot: number;
}

export interface GroupVault {
  id: string;           // vault_id as string
  creator: string;
  token: AssetCode;
  members: MemberEntry[];
  unlockTime: number;   // unix seconds
  fundingDeadline: number;
  lockType: "strict" | "penalty";
  penaltyPercent: number;
  totalSize: number;    // human-readable
  depositedCount: number;
  poolBalance: number;  // human-readable
  status: GroupVaultStatus;
  // local metadata
  name?: string;
  // ZK privacy fields
  isZk?: boolean;
  memberCount?: number;
  /** This user's slot index in a ZK vault */
  slotIndex?: number;
  /** This user's member secret (needed for ZK deposit) */
  memberSecret?: string;
  /** This user's deposit nullifier (needed for ZK withdraw/claim) */
  nullifierHex?: string;
  /** Blinding factor for this deposit (kept locally, revealed only at withdrawal) */
  blindingR?: string;
  /** Member secrets generated by the creator (for sharing) */
  memberSecrets?: ZkMemberSecret[];
}

export type GroupTxnType = "group-deposit" | "group-withdraw" | "group-cancel" | "group-claim";

export interface GroupTransaction {
  id: string;
  vaultId: string;
  token: AssetCode;
  type: GroupTxnType;
  amount: number;
  at: string;
}

interface GroupVaultState {
  vaults: GroupVault[];
  transactions: GroupTransaction[];
  loading: boolean;
  error: string | null;

  fetchVaults: () => Promise<void>;
  fetchVaultById: (vaultId: string) => Promise<void>;
  createGroupVault: (input: {
    name?: string;
    token: AssetCode;
    members: { address: string; amount: number }[];
    durationDays: number;
    fundingHours: number;
    lockType: "strict" | "penalty";
    penaltyPercent: number;
  }) => Promise<GroupVault>;
  deposit: (vaultId: string) => Promise<void>;
  withdraw: (vaultId: string) => Promise<void>;
  cancel: (vaultId: string) => Promise<void>;
  claimPool: (vaultId: string) => Promise<void>;

  // ─── ZK Privacy methods ─────────────────────────────────────────────────
  createGroupVaultZk: (input: {
    name?: string;
    token: AssetCode;
    members: { address: string; amount: number }[];
    durationDays: number;
    fundingHours: number;
    lockType: "strict" | "penalty";
    penaltyPercent: number;
  }) => Promise<GroupVault>;
  fetchZkVaultById: (vaultId: string) => Promise<void>;
  saveMemberSecret: (vaultId: string, secret: string, commitment: string, slot: number) => void;
  depositZk: (vaultId: string) => Promise<void>;
  /** Deposit into a ZK vault using UltraHonk proof bytes + public inputs */
  depositZkUltraHonk: (vaultId: string, proofBytesHex: string, publicInputsHex: string) => Promise<void>;
  withdrawZk: (vaultId: string) => Promise<void>;
  claimPoolZk: (vaultId: string) => Promise<void>;

  reset: () => void;
}

// ─── Token address → AssetCode ────────────────────────────────────────────────

const TOKEN_TO_ASSET: Record<string, AssetCode> = Object.fromEntries(
  Object.entries(TOKEN_ADDRESS).map(([code, addr]) => [addr, code as AssetCode]),
);
function tokenToAsset(addr: string): AssetCode { return TOKEN_TO_ASSET[addr] ?? "XLM"; }

function stateToStatus(state: CcpVaultState | string): GroupVaultStatus {
  const s = typeof state === "string" ? state : Object.keys(state as object)[0];
  if (s === "FundingOpen") return "funding";
  if (s === "ActiveLocked") return "active";
  if (s === "SettlementReady") return "settlement";
  if (s === "Resolved") return "resolved";
  if (s === "Cancelled") return "cancelled";
  return "funding"; // safe default — never hide a vault as cancelled incorrectly
}

// ─── Store ────────────────────────────────────────────────────────────────────

export const useGroupVaultStore = create<GroupVaultState>()(
  persist(
    (set, get) => ({
      vaults: [],
      transactions: [],
      loading: false,
      error: null,

      fetchVaults: async () => {
        const address = useWalletStore.getState().address;
        if (!address) return;
        set({ loading: true, error: null });
        try {
          const [memberIds, creatorIds] = await Promise.all([
            getVaultsByMember(address),
            getVaultsByCreator(address),
          ]);
          // Deduplicate
          const allIds = [...new Set([...memberIds, ...creatorIds].map(String))].map(BigInt);

          const vaults: GroupVault[] = [];
          for (const id of allIds) {
            const onChain = await getGroupVault(id);
            if (!onChain) continue;

            // Fetch member states
            const members: MemberEntry[] = [];
            for (const memberAddr of onChain.members) {
              const rec = await getMemberState(id, memberAddr);
              const obligationAmount = (onChain.obligations as any)[memberAddr] ?? BigInt(0);
              members.push({
                address: memberAddr,
                amount: rec ? fromStroops(rec.amount) : fromStroops(BigInt(obligationAmount)),
                state: rec ? memberStateLabel(rec.state) : "Committed",
                rawState: rec ? rec.state : { Committed: undefined as any },
              });
            }

            const poolBalance = await getCcpPoolBalance(id);

            vaults.push({
              id: String(id),
              creator: onChain.creator,
              token: tokenToAsset(onChain.token),
              members,
              unlockTime: Number(onChain.unlock_time),
              fundingDeadline: Number(onChain.funding_deadline),
              lockType: typeof onChain.lock_type === "string"
                ? (onChain.lock_type === "Strict" ? "strict" : "penalty")
                : ("Strict" in (onChain.lock_type as object) ? "strict" : "penalty"),
              penaltyPercent: bpsToPercent(onChain.penalty_rate),
              totalSize: fromStroops(onChain.total_size),
              depositedCount: onChain.deposited_count,
              poolBalance,
              status: stateToStatus(onChain.state),
            });
          }

          // Preserve local names
          const existing = get().vaults;
          const merged = vaults.map((v) => {
            const local = existing.find((e) => e.id === v.id);
            return local ? { ...v, name: local.name } : v;
          });

          // Preserve ZK vaults — they're not returned by standard on-chain queries
          for (const existingVault of existing) {
            if (existingVault.isZk && !merged.some(m => m.id === existingVault.id)) {
              merged.push(existingVault);
            }
          }

          set({ vaults: merged, loading: false });
        } catch (e) {
          set({ loading: false, error: String(e) });
        }
      },

      fetchVaultById: async (vaultId: string) => {
        set({ loading: true, error: null });
        try {
          const id = BigInt(vaultId);
          const onChain = await getGroupVault(id);
          if (!onChain) { set({ loading: false }); return; }

          const members: MemberEntry[] = [];
          for (const memberAddr of onChain.members) {
            const rec = await getMemberState(id, memberAddr);
            const obligationAmount = (onChain.obligations as any)[memberAddr] ?? BigInt(0);
            members.push({
              address: memberAddr,
              amount: rec ? fromStroops(rec.amount) : fromStroops(BigInt(obligationAmount)),
              state: rec ? memberStateLabel(rec.state) : "Committed",
              rawState: rec ? rec.state : { Committed: undefined as any },
            });
          }

          const poolBalance = await getCcpPoolBalance(id);
          const fresh: GroupVault = {
            id: vaultId,
            creator: onChain.creator,
            token: tokenToAsset(onChain.token),
            members,
            unlockTime: Number(onChain.unlock_time),
            fundingDeadline: Number(onChain.funding_deadline),
            lockType: typeof onChain.lock_type === "string"
              ? (onChain.lock_type === "Strict" ? "strict" : "penalty")
              : ("Strict" in (onChain.lock_type as object) ? "strict" : "penalty"),
            penaltyPercent: bpsToPercent(onChain.penalty_rate),
            totalSize: fromStroops(onChain.total_size),
            depositedCount: onChain.deposited_count,
            poolBalance,
            status: stateToStatus(onChain.state),
          };

          // Merge with existing (preserve name)
          const existing = get().vaults;
          const local = existing.find((e) => e.id === vaultId);
          const merged = local ? { ...fresh, name: local.name } : fresh;
          const updated = existing.some((e) => e.id === vaultId)
            ? existing.map((e) => e.id === vaultId ? merged : e)
            : [merged, ...existing];

          set({ vaults: updated, loading: false });
        } catch (e) {
          set({ loading: false, error: String(e) });
        }
      },

      createGroupVault: async ({ name, token, members, durationDays, fundingHours, lockType, penaltyPercent }) => {
        const walletStore = useWalletStore.getState();
        const address = walletStore.address;
        if (!address) throw new Error("Wallet not connected");

        // Get the actual ledger timestamp to avoid browser clock skew
        // Add 120s buffer to account for tx propagation delay (~5s ledger close time)
        const ledgerNow = Math.floor(Date.now() / 1000);
        const unlockTime = ledgerNow + durationDays * 86_400 + 3600;
        const fundingDeadline = ledgerNow + fundingHours * 3_600;
        if (fundingDeadline >= unlockTime) {
          throw new Error("Funding deadline must be before unlock time. Increase lock duration or reduce funding window.");
        }

        const txXdr = await buildCreateGroupVault(
          address,
          token,
          members.map((m) => m.address),
          members.map((m) => m.amount),
          unlockTime,
          fundingDeadline,
          lockType,
          penaltyPercent,
        );

        const signedXdr = await walletStore.signTransaction(txXdr);
        const result = await submitCcpTx(signedXdr);

        let vaultId = "0";
        if (result.status === "SUCCESS" && result.returnValue) {
          const mod = await import("@stellar/stellar-sdk");
          const s: any = (mod as any).default ?? mod;
          vaultId = String(s.scValToNative(result.returnValue) as bigint);
        }

        const vault: GroupVault = {
          id: vaultId,
          name,
          creator: address,
          token,
          members: members.map((m) => ({
            address: m.address,
            amount: m.amount,
            state: "Committed",
            rawState: { Committed: undefined as any },
          })),
          unlockTime,
          fundingDeadline,
          lockType,
          penaltyPercent: lockType === "strict" ? 0 : penaltyPercent,
          totalSize: members.reduce((s, m) => s + m.amount, 0),
          depositedCount: 0,
          poolBalance: 0,
          status: "funding",
        };

        const createTxn: GroupTransaction = {
          id: `gpt_${crypto.randomUUID()}`,
          vaultId: vault.id,
          token: vault.token,
          type: "group-deposit",
          amount: -vault.totalSize,
          at: new Date().toISOString(),
        };
        set({ vaults: [vault, ...get().vaults], transactions: [createTxn, ...get().transactions] });
        // Use fetchVaultById to get fresh chain data — more reliable than index query
        setTimeout(() => get().fetchVaultById(vaultId), 5000);
        return vault;
      },

      deposit: async (vaultId) => {
        const walletStore = useWalletStore.getState();
        const address = walletStore.address;
        if (!address) throw new Error("Wallet not connected");
        const txXdr = await buildDeposit(address, BigInt(vaultId));
        const signedXdr = await walletStore.signTransaction(txXdr);
        await submitCcpTx(signedXdr);
        const vault = get().vaults.find(v => v.id === vaultId);
        const memberAmount = vault?.members.find(m => m.address === address)?.amount ?? 0;
        const txn: GroupTransaction = {
          id: `gpt_${crypto.randomUUID()}`,
          vaultId,
          token: vault?.token ?? "XLM",
          type: "group-deposit",
          amount: -memberAmount,
          at: new Date().toISOString(),
        };
        if (memberAmount > 0) walletStore.adjustBalance(vault!.token, -memberAmount);
        set({ transactions: [txn, ...get().transactions] });
        setTimeout(() => get().fetchVaults(), 3000);
      },

      withdraw: async (vaultId) => {
        const walletStore = useWalletStore.getState();
        const address = walletStore.address;
        if (!address) throw new Error("Wallet not connected");
        const txXdr = await buildCcpWithdraw(address, BigInt(vaultId));
        const signedXdr = await walletStore.signTransaction(txXdr);
        await submitCcpTx(signedXdr);
        const vault = get().vaults.find(v => v.id === vaultId);
        const memberAmount = vault?.members.find(m => m.address === address)?.amount ?? 0;
        const txn: GroupTransaction = {
          id: `gpt_${crypto.randomUUID()}`,
          vaultId,
          token: vault?.token ?? "XLM",
          type: "group-withdraw",
          amount: memberAmount,
          at: new Date().toISOString(),
        };
        if (memberAmount > 0) walletStore.adjustBalance(vault!.token, memberAmount);
        set({ transactions: [txn, ...get().transactions] });
        setTimeout(() => get().fetchVaults(), 3000);
      },

      cancel: async (vaultId) => {
        const walletStore = useWalletStore.getState();
        const txXdr = await buildCancel(BigInt(vaultId));
        const signedXdr = await walletStore.signTransaction(txXdr);
        await submitCcpTx(signedXdr);
        const vault = get().vaults.find(v => v.id === vaultId);
        const address = walletStore.address;
        const memberAmount = vault?.members.find(m => m.address === address)?.amount ?? 0;
        const txn: GroupTransaction = {
          id: `gpt_${crypto.randomUUID()}`,
          vaultId,
          token: vault?.token ?? "XLM",
          type: "group-cancel",
          amount: memberAmount,
          at: new Date().toISOString(),
        };
        if (memberAmount > 0) walletStore.adjustBalance(vault!.token, memberAmount);
        set({ transactions: [txn, ...get().transactions] });
        setTimeout(() => get().fetchVaults(), 3000);
      },

      claimPool: async (vaultId) => {
        const walletStore = useWalletStore.getState();
        const address = walletStore.address;
        if (!address) throw new Error("Wallet not connected");
        const txXdr = await buildClaimPool(address, BigInt(vaultId));
        const signedXdr = await walletStore.signTransaction(txXdr);
        await submitCcpTx(signedXdr);
        const vault = get().vaults.find(v => v.id === vaultId);
        const poolShare = vault ? vault.poolBalance / (vault.members.filter(m => m.state === "Active" || m.state === "Withdrawn").length || 1) : 0;
        const txn: GroupTransaction = {
          id: `gpt_${crypto.randomUUID()}`,
          vaultId,
          token: vault?.token ?? "XLM",
          type: "group-claim",
          amount: poolShare,
          at: new Date().toISOString(),
        };
        set({ transactions: [txn, ...get().transactions] });
        setTimeout(() => get().fetchVaults(), 3000);
      },

      // ─── ZK Privacy methods ─────────────────────────────────────────────────

      createGroupVaultZk: async ({ name, token, members, durationDays, fundingHours, lockType, penaltyPercent }) => {
        const walletStore = useWalletStore.getState();
        const address = walletStore.address;
        if (!address) throw new Error("Wallet not connected");

        // Generate address-derived member secrets and amount-inclusive commitments
        const secrets: ZkMemberSecret[] = [];
        const commitments: string[] = [];
        for (let i = 0; i < members.length; i++) {
          const secret = await deriveSecretFromAddress(members[i].address);
          const stroops = toStroops(members[i].amount);
          // commitment = SHA-256(DOMAIN_COMMIT || amount_le || secret) — matches contract's commit()
          const commitment = await computeZkDepositCommitment(stroops, secret);
          secrets.push({ address: members[i].address, secret, commitment, slot: i });
          commitments.push(commitment);
        }

        const ledgerNow = Math.floor(Date.now() / 1000);
        const unlockTime = ledgerNow + durationDays * 86_400 + 3600;
        const fundingDeadline = ledgerNow + fundingHours * 3_600;
        if (fundingDeadline >= unlockTime) {
          throw new Error("Funding deadline must be before unlock time. Increase lock duration or reduce funding window.");
        }

        const txXdr = await buildCreateGroupVaultZk(
          address, token, commitments,
          members.map((m) => m.amount),
          unlockTime, fundingDeadline, lockType, penaltyPercent,
        );

        const signedXdr = await walletStore.signTransaction(txXdr);
        const result = await submitCcpTx(signedXdr);

        let vaultId = "0";
        if (result.status === "SUCCESS" && result.returnValue) {
          const mod = await import("@stellar/stellar-sdk");
          const s: any = (mod as any).default ?? mod;
          vaultId = String(s.scValToNative(result.returnValue) as bigint);
        }

        const vault: GroupVault = {
          id: vaultId, name,
          isZk: true,
          memberCount: members.length,
          memberSecrets: secrets,
          creator: address, token,
          members: members.map((m, i) => ({
            address: m.address,
            amount: m.amount,
            state: "Committed",
            rawState: { Committed: undefined as any },
          })),
          unlockTime, fundingDeadline, lockType,
          penaltyPercent: lockType === "strict" ? 0 : penaltyPercent,
          totalSize: members.reduce((s, m) => s + m.amount, 0),
          depositedCount: 0, poolBalance: 0, status: "funding",
        };

        const txn: GroupTransaction = {
          id: `gpt_${crypto.randomUUID()}`,
          vaultId: vault.id,
          token: vault.token,
          type: "group-deposit",
          amount: -vault.totalSize,
          at: new Date().toISOString(),
        };
        set({
          vaults: [vault, ...get().vaults],
          transactions: [txn, ...get().transactions],
        });
        return vault;
      },

      fetchZkVaultById: async (vaultId: string) => {
        set({ loading: true, error: null });
        try {
          const id = BigInt(vaultId);
          const privacyMode = await getVaultPrivacyMode(id);
          if (!privacyMode) { set({ loading: false }); return; }

          const zkVault = await getZkVault(id);
          if (!zkVault) { set({ loading: false }); return; }

          const memberCount = zkVault.member_count;
          const members: MemberEntry[] = [];
          for (let slot = 0; slot < memberCount; slot++) {
            const rec = await getZkMemberRecord(id, slot);
            const obligation = (zkVault.slot_obligations as any)[slot] ?? BigInt(0);
            members.push({
              address: `slot-${slot}`,
              amount: rec ? fromStroops(rec.amount) : fromStroops(BigInt(obligation)),
              state: rec ? memberStateLabel(rec.state) : "Committed",
              rawState: rec ? rec.state : { Committed: undefined as any },
              commitment: rec ? rec.member_commitment : undefined,
              obligationStroops: rec ? String(rec.amount) : String(obligation),
            });
          }

          const existing = get().vaults;
          const local = existing.find((e) => e.id === vaultId);

          const fresh: GroupVault = {
            id: vaultId,
            isZk: true,
            memberCount,
            creator: zkVault.creator,
            token: tokenToAsset(zkVault.token),
            members,
            unlockTime: Number(zkVault.unlock_time),
            fundingDeadline: Number(zkVault.funding_deadline),
            lockType: "Strict" in (zkVault.lock_type as object) ? "strict" : "penalty",
            penaltyPercent: bpsToPercent(zkVault.penalty_rate),
            totalSize: fromStroops(zkVault.total_size),
            depositedCount: zkVault.deposited_count,
            poolBalance: 0,
            status: stateToStatus(zkVault.state),
            // Preserve local-only fields
            name: local?.name,
            slotIndex: local?.slotIndex,
            memberSecret: local?.memberSecret,
            nullifierHex: local?.nullifierHex,
            blindingR: local?.blindingR,
            memberSecrets: local?.memberSecrets,
          };

          const poolBal = await getCcpPoolBalance(id);
          fresh.poolBalance = poolBal;

          const updated = existing.some((e) => e.id === vaultId)
            ? existing.map((e) => e.id === vaultId ? fresh : e)
            : [fresh, ...existing];

          set({ vaults: updated, loading: false });
        } catch (e) {
          set({ loading: false, error: String(e) });
        }
      },

      saveMemberSecret: (vaultId, secret, commitment, slot) => {
        set({
          vaults: get().vaults.map((v) =>
            v.id === vaultId ? {
              ...v,
              isZk: true,
              memberSecret: secret,
              memberCommitment: commitment,
              slotIndex: slot,
            } : v
          ),
        });
      },

      depositZk: async (vaultId) => {
        const walletStore = useWalletStore.getState();
        const address = walletStore.address;
        if (!address) throw new Error("Wallet not connected");

        const vault = get().vaults.find(v => v.id === vaultId);
        if (!vault) throw new Error("Vault not found");
        if (vault.slotIndex === undefined) throw new Error("Slot index not set — unlock your membership first");
        const myMember = vault.members[vault.slotIndex];
        if (!myMember) throw new Error("Member slot not found");
        const amountStroops = toStroops(myMember.amount);

        // Derive blinding factor deterministically from wallet + vault + slot.
        // This prevents permanent fund loss on localStorage clear.
        const blindingR = await deriveZkBlindingFactor(address, BigInt(vaultId), vault.slotIndex);
        const proof = await buildZkDepositProof(amountStroops, BigInt(vaultId), blindingR);

        const txXdr = await buildDepositZk(address, BigInt(vaultId), vault.slotIndex, proof);
        const signedXdr = await walletStore.signTransaction(txXdr);
        await submitCcpTx(signedXdr);

        const txn: GroupTransaction = {
          id: `gpt_${crypto.randomUUID()}`,
          vaultId, token: vault.token,
          type: "group-deposit",
          amount: -myMember.amount,
          at: new Date().toISOString(),
        };
        walletStore.adjustBalance(vault.token, -myMember.amount);
        set({
          transactions: [txn, ...get().transactions],
          vaults: get().vaults.map(v =>
            v.id === vaultId ? { ...v, nullifierHex: proof.nullifier, blindingR: proof.blinding_r } : v
          ),
        });
        setTimeout(() => get().fetchZkVaultById(vaultId), 4000);
      },

      depositZkUltraHonk: async (vaultId, proofBytesHex, publicInputsHex) => {
        const walletStore = useWalletStore.getState();
        const address = walletStore.address;
        if (!address) throw new Error("Wallet not connected");

        const vault = get().vaults.find(v => v.id === vaultId);
        if (!vault) throw new Error("Vault not found");
        if (vault.slotIndex === undefined) throw new Error("Slot index not set — unlock your membership first");
        const myMember = vault.members[vault.slotIndex];
        if (!myMember) throw new Error("Member slot not found");

        const txXdr = await buildDepositZkUltraHonk(address, BigInt(vaultId), proofBytesHex, publicInputsHex);
        const signedXdr = await walletStore.signTransaction(txXdr);
        await submitCcpTx(signedXdr);

        const txn: GroupTransaction = {
          id: `gpt_${crypto.randomUUID()}`,
          vaultId, token: vault.token,
          type: "group-deposit",
          amount: -myMember.amount,
          at: new Date().toISOString(),
        };
        walletStore.adjustBalance(vault.token, -myMember.amount);
        set({ transactions: [txn, ...get().transactions] });
        setTimeout(() => get().fetchZkVaultById(vaultId), 4000);
      },

      withdrawZk: async (vaultId) => {
        const walletStore = useWalletStore.getState();
        const address = walletStore.address;
        if (!address) throw new Error("Wallet not connected");

        const vault = get().vaults.find(v => v.id === vaultId);
        if (!vault || !vault.nullifierHex) throw new Error("Nullifier not found — deposit first");
        if (!vault.blindingR) throw new Error("Blinding factor not found — needed for ownership proof");

        let exitProof: any = undefined;
        if (vault.status === "active" && vault.lockType === "penalty") {
          const myMember = vault.slotIndex !== undefined ? vault.members[vault.slotIndex] : vault.members[0];
          exitProof = await buildZkEarlyExitProof(toStroops(myMember.amount), vault.penaltyPercent * 100);
        }

        const txXdr = await buildWithdrawZk(address, BigInt(vaultId), vault.nullifierHex, vault.blindingR, exitProof);
        const signedXdr = await walletStore.signTransaction(txXdr);
        await submitCcpTx(signedXdr);

        const txn: GroupTransaction = {
          id: `gpt_${crypto.randomUUID()}`,
          vaultId, token: vault.token,
          type: "group-withdraw",
          amount: 0, // amount determined on chain
          at: new Date().toISOString(),
        };
        set({ transactions: [txn, ...get().transactions] });
        setTimeout(() => get().fetchZkVaultById(vaultId), 4000);
      },

      claimPoolZk: async (vaultId) => {
        const walletStore = useWalletStore.getState();
        const address = walletStore.address;
        if (!address) throw new Error("Wallet not connected");

        const vault = get().vaults.find(v => v.id === vaultId);
        if (!vault || !vault.nullifierHex) throw new Error("Nullifier not found");
        if (!vault.blindingR) throw new Error("Blinding factor not found — needed for ownership proof");

        const txXdr = await buildClaimPoolZk(address, BigInt(vaultId), vault.nullifierHex, vault.blindingR);
        const signedXdr = await walletStore.signTransaction(txXdr);
        await submitCcpTx(signedXdr);

        const txn: GroupTransaction = {
          id: `gpt_${crypto.randomUUID()}`,
          vaultId, token: vault.token,
          type: "group-claim",
          amount: 0,
          at: new Date().toISOString(),
        };
        set({ transactions: [txn, ...get().transactions] });
        setTimeout(() => get().fetchZkVaultById(vaultId), 4000);
      },

      reset: () => set({ vaults: [], transactions: [], loading: false, error: null }),
    }),
    {
      name: "group-vault-store-v2",
      onRehydrateStorage: () => (state) => {
        if (!state) return;
        const { vaults, transactions } = state;
        const existing = transactions ?? [];
        const generated: GroupTransaction[] = [];
        for (const v of vaults) {
          if (!existing.some(t => t.vaultId === v.id && t.type === "group-deposit")) {
            generated.push({
              id: `gpt_${crypto.randomUUID()}`,
              vaultId: v.id,
              token: v.token,
              type: "group-deposit",
              amount: -v.totalSize,
              at: new Date().toISOString(),
            });
          }
          if ((v.status === "resolved" || v.status === "cancelled") &&
              !existing.some(t => t.vaultId === v.id && (t.type === "group-withdraw" || t.type === "group-cancel"))) {
            generated.push({
              id: `gpt_${crypto.randomUUID()}`,
              vaultId: v.id,
              token: v.token,
              type: v.status === "cancelled" ? "group-cancel" : "group-withdraw",
              amount: v.totalSize,
              at: new Date().toISOString(),
            });
          }
        }
        if (generated.length > 0) {
          useGroupVaultStore.setState({ transactions: [...generated, ...existing] });
        }
      },
    },
  ),
);
